-- SWITCH TO DATABASE  (MYSQL)
USE SAKILA; 
-- SELECT ALL ROWS FROM ACTOR TABLE
SELECT * FROM ACTOR;

-- CREATE DATABASE
CREATE DATABASE  JBEDB;
USE JBEDB;
CREATE TABLE PRODUCTS(PRODUCT_ID INT, PRODUCT_NAME CHAR(50), PRICE FLOAT);
INSERT INTO PRODUCTS VALUES (1, 'LIMITLESS',55.50);
INSERT INTO PRODUCTS VALUES (2, 'SWW',155.50);
INSERT INTO PRODUCTS VALUES (3, 'TPON',155.50);
INSERT INTO PRODUCTS VALUES (4, 'LOY',780.50);
UPDATE PRODUCTS SET PRODUCT_NAME = 'MSFM' WHERE PRODUCT_ID = 4;
DELETE FROM PRODUCTS WHERE PRODUCT_ID = 4;
SELECT * FROM PRODUCTS;
DELETE FROM PRODUCTS;