-- SWITCH TO DATABASE  (MYSQL)
USE SAKILA; 
-- SELECT ALL ROWS FROM ACTOR TABLE
SELECT * FROM ACTOR;

-- CREATE DATABASE
CREATE DATABASE  JBEDB;
USE JBEDB;
CREATE TABLE PRODUCTS(PRODUCT_ID INT, PRODUCT_NAME CHAR(50), PRICE FLOAT);
INSERT INTO PRODUCTS VALUES (1, 'LIMITLESS',55.50);
INSERT INTO PRODUCTS VALUES (2, 'SWW',155.50);
SELECT * FROM PRODUCTS;
DELETE FROM PRODUCTS;